services:
  - type: worker
    name: trendcast-scraper-worker
    env: docker
    region: ohio
    dockerfilePath: ./Dockerfile.worker
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
